"""
Django settings for api_todo project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path

# Caminho base do projeto (diretório raiz)
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================
# Configurações básicas
# ==========================

# Chave secreta do Django. ⚠️ NUNCA deixe isso público em produção!
SECRET_KEY = 'django-insecure-9bk_-56k2okk5t2erzoowonwh0&&3b03cemqkq^yls8yjvb(z_'

# Ativa o modo de debug. ⚠️ Deve ser False em produção.
DEBUG = True

# Lista de hosts permitidos a acessar sua aplicação. Em produção, defina os domínios permitidos.
ALLOWED_HOSTS = []


# ==========================
# Aplicativos instalados
# ==========================

INSTALLED_APPS = [
    # Apps nativos do Django
    'django.contrib.admin',          # Admin do Django
    'django.contrib.auth',           # Sistema de autenticação
    'django.contrib.contenttypes',   # Tipagem de conteúdo
    'django.contrib.sessions',       # Gerenciamento de sessões
    'django.contrib.messages',       # Sistema de mensagens
    'django.contrib.staticfiles',    # Gerenciamento de arquivos estáticos (CSS, JS, etc.)

    # Framework para criação de APIs
    'rest_framework',

    # Seu app local
    'app.apps.AppConfig',
]


# ==========================
# Middleware
# ==========================
# Camadas que processam requisições e respostas no Django

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',             # Segurança (SSL, HSTS, etc.)
    'django.contrib.sessions.middleware.SessionMiddleware',      # Gerencia sessões de usuários
    'django.middleware.common.CommonMiddleware',                 # Middleware comum (redirecionamento e outras regras)
    'django.middleware.csrf.CsrfViewMiddleware',                 # Protege contra CSRF (Cross-Site Request Forgery)
    'django.contrib.auth.middleware.AuthenticationMiddleware',   # Autenticação de usuários
    'django.contrib.messages.middleware.MessageMiddleware',      # Sistema de mensagens
    'django.middleware.clickjacking.XFrameOptionsMiddleware',    # Protege contra clickjacking
]


# ==========================
# Arquivo de rotas principal
# ==========================

ROOT_URLCONF = 'api_todo.urls'


# ==========================
# Templates (HTML)
# ==========================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Motor de templates
        'DIRS': [],                                                     # Diretórios adicionais de templates
        'APP_DIRS': True,                                               # Usa os templates dentro dos apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',           # Acesso ao objeto request nos templates
                'django.contrib.auth.context_processors.auth',          # Informações do usuário autenticado
                'django.contrib.messages.context_processors.messages',  # Sistema de mensagens
            ],
        },
    },
]


# ==========================
# Configuração do WSGI
# ==========================

WSGI_APPLICATION = 'api_todo.wsgi.application'


# ==========================
# Banco de Dados
# ==========================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',   # Banco SQLite
        'NAME': BASE_DIR / 'db.sqlite3',          # Caminho do arquivo do banco
    }
}


# ==========================
# Validação de senhas
# ==========================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Valida similaridade com atributos do usuário
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',            # Tamanho mínimo
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',           # Senhas comuns
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',          # Apenas números
    },
]


# ==========================
# Internacionalização
# ==========================

LANGUAGE_CODE = 'en-us'    # Linguagem padrão

TIME_ZONE = 'UTC'          # Fuso horário padrão

USE_I18N = True            # Ativa internacionalização

USE_TZ = True              # Usa timezone


# ==========================
# Arquivos estáticos
# ==========================

STATIC_URL = 'static/'


# ==========================
# Configurações padrões
# ==========================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Tipo padrão de chave primária (BigInt)
